# Generated by Django 4.0 on 2021-12-16 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institut', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='user',
        ),
    ]
